import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useOrganization } from "@/hooks/useOrganization";
import { toast } from "sonner";

export interface CRMActivity {
  id: string;
  organization_id: string;
  activity_number: string;
  subject: string;
  status: string;
  priority: string;
  type: string | null;
  due_date: string | null;
  customer_id: string | null;
  assigned_to: string | null;
  description: string | null;
  created_at: string;
  updated_at: string;
  // Joined customer data
  customer?: {
    id: string;
    first_name: string | null;
    last_name: string | null;
    email: string;
    company_name: string;
  } | null;
  // Joined assignee data
  assignee?: {
    id: string;
    full_name: string;
  } | null;
}

export const useActivities = () => {
  const { organization } = useOrganization();
  const queryClient = useQueryClient();

  const { data: activities = [], isLoading } = useQuery({
    queryKey: ["crm_activities", organization?.id],
    queryFn: async () => {
      if (!organization?.id) return [];
      
      const { data, error } = await supabase
        .from("crm_activities")
        .select(`
          *,
          customer:customers(id, first_name, last_name, email, company_name),
          assignee:profiles!crm_activities_assigned_to_fkey(id, full_name)
        `)
        .eq("organization_id", organization.id)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data as CRMActivity[];
    },
    enabled: !!organization?.id,
  });

  const addActivity = useMutation({
    mutationFn: async (activityData: {
      subject: string;
      status?: string;
      priority?: string;
      type?: string;
      due_date?: string;
      customer_id?: string;
      assigned_to?: string;
      description?: string;
    }) => {
      if (!organization?.id) throw new Error("No organization");

      const { data, error } = await supabase
        .from("crm_activities")
        .insert({
          organization_id: organization.id,
          activity_number: "", // Will be auto-generated by trigger
          subject: activityData.subject,
          status: activityData.status || "not_started",
          priority: activityData.priority || "normal",
          type: activityData.type || null,
          due_date: activityData.due_date || null,
          customer_id: activityData.customer_id || null,
          assigned_to: activityData.assigned_to || null,
          description: activityData.description || null,
        })
        .select()
        .single();

      if (error) throw error;
      return data as CRMActivity;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["crm_activities", organization?.id] });
    },
    onError: (error) => {
      toast.error("Failed to create activity: " + error.message);
    },
  });

  const updateActivity = useMutation({
    mutationFn: async (activityData: Partial<CRMActivity> & { id: string }) => {
      const { id, customer, assignee, ...updateData } = activityData;

      const { data, error } = await supabase
        .from("crm_activities")
        .update(updateData)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data as CRMActivity;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["crm_activities", organization?.id] });
    },
    onError: (error) => {
      toast.error("Failed to update activity: " + error.message);
    },
  });

  const deleteActivity = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("crm_activities")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["crm_activities", organization?.id] });
    },
    onError: (error) => {
      toast.error("Failed to delete activity: " + error.message);
    },
  });

  return { activities, isLoading, addActivity, updateActivity, deleteActivity };
};
