import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useOrganization } from "@/hooks/useOrganization";
import { toast } from "sonner";

export interface CRMCase {
  id: string;
  organization_id: string;
  case_number: string;
  subject: string;
  status: string;
  priority: string;
  type: string | null;
  case_origin: string | null;
  product_name: string | null;
  email: string | null;
  phone: string | null;
  reported_by: string | null;
  customer_id: string | null;
  assigned_to: string | null;
  description: string | null;
  created_at: string;
  updated_at: string;
  // Joined customer data
  customer?: {
    id: string;
    first_name: string | null;
    last_name: string | null;
    email: string;
    company_name: string;
  } | null;
  // Joined assignee data
  assignee?: {
    id: string;
    full_name: string;
  } | null;
}

export const useCases = () => {
  const { organization } = useOrganization();
  const queryClient = useQueryClient();

  const { data: cases = [], isLoading } = useQuery({
    queryKey: ["crm_cases", organization?.id],
    queryFn: async () => {
      if (!organization?.id) return [];
      
      const { data, error } = await supabase
        .from("crm_cases")
        .select(`
          *,
          customer:customers(id, first_name, last_name, email, company_name),
          assignee:profiles!crm_cases_assigned_to_fkey(id, full_name)
        `)
        .eq("organization_id", organization.id)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data as CRMCase[];
    },
    enabled: !!organization?.id,
  });

  const addCase = useMutation({
    mutationFn: async (caseData: {
      subject: string;
      status?: string;
      priority?: string;
      type?: string;
      case_origin?: string;
      product_name?: string;
      email?: string;
      phone?: string;
      reported_by?: string;
      customer_id?: string;
      assigned_to?: string;
      description?: string;
    }) => {
      if (!organization?.id) throw new Error("No organization");

      const { data, error } = await supabase
        .from("crm_cases")
        .insert({
          organization_id: organization.id,
          case_number: "", // Will be auto-generated by trigger
          subject: caseData.subject,
          status: caseData.status || "new",
          priority: caseData.priority || "medium",
          type: caseData.type || null,
          case_origin: caseData.case_origin || null,
          product_name: caseData.product_name || null,
          email: caseData.email || null,
          phone: caseData.phone || null,
          reported_by: caseData.reported_by || null,
          customer_id: caseData.customer_id || null,
          assigned_to: caseData.assigned_to || null,
          description: caseData.description || null,
        })
        .select()
        .single();

      if (error) throw error;
      return data as CRMCase;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["crm_cases", organization?.id] });
    },
    onError: (error) => {
      toast.error("Failed to create case: " + error.message);
    },
  });

  const updateCase = useMutation({
    mutationFn: async (caseData: Partial<CRMCase> & { id: string }) => {
      const { id, customer, assignee, ...updateData } = caseData;

      const { data, error } = await supabase
        .from("crm_cases")
        .update(updateData)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data as CRMCase;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["crm_cases", organization?.id] });
    },
    onError: (error) => {
      toast.error("Failed to update case: " + error.message);
    },
  });

  const deleteCase = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("crm_cases")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["crm_cases", organization?.id] });
    },
    onError: (error) => {
      toast.error("Failed to delete case: " + error.message);
    },
  });

  return { cases, isLoading, addCase, updateCase, deleteCase };
};
