// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiikjhvzlwzysbtzhdcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpaWtqaHZ6bHd6eXNidHpoZGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MTk2NzMsImV4cCI6MjA4NDk5NTY3M30.pBy01M70ltLCmrxqJPkZIsqLgS-61995zhQB0Kgec58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});